version: '3'                                    # 指定 docker-compose.yml 文件的写法格式
services:                                       # 多个容器集合
  jenkins:
    user: root # 为了避免 volumes 下 /usr/local/volumes/jenkins_home 的权限问题，直接使用 root 用户
    image: jenkins/jenkins:lts-jdk11
    restart: always
    container_name: jenkins_container
    volumes:
      - /usr/local/volumes/jenkins_home:/var/jenkins_home # 这样拉下来的项目会在容器的 /var/jenkins_home/workspace/blog-sys
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker                 # 这是为了我们可以在容器内使用docker命令
#      - ./docker-compose:/usr/local/bin/docker-compose     # 同样的这是为了使用docker-compose命令
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose     # 同样的这是为了使用docker-compose命令
    ports:
      - "9090:8080" # 其他端口会打不开网页？
