const BaseController = require('../baseController')
const register = require('./register')
const uInfo = require('./info')
const userInfo = require('./userInfo')
const update = require('./update')
const adminLogin = require('./adminLogin')
const login = require('./login')
const logout = require('./logout')
const all = require('./all')
const manageList = require('./list')
const operateLock = require('./operateLock')
const updateAvatar = require('./updateAvatar')
const operateFollow = require('./operateFollow')
const setGroup = require('./setGroup')
const getMediaList = require('./getMediaList')
const friends = require('./friends')
const markBlogList = require('./markBlogList')
const myCommentList = require('./myCommentList')

class UserController extends BaseController{
  constructor() {
    super()
    this.register = register.bind(this)
    this.info = uInfo.bind(this)
    this.userInfo = userInfo.bind(this)
    this.update = update.bind(this)
    this.adminLogin = adminLogin.bind(this)
    this.login = login.bind(this)
    this.logout = logout.bind(this)
    this.all = all.bind(this)
    this.list = manageList.bind(this)
    this.operateLock = operateLock.bind(this)
    this.updateAvatar = updateAvatar.bind(this)
    this.operateFollow = operateFollow.bind(this)
    this.setGroup = setGroup.bind(this)
    this.getMediaList = getMediaList.bind(this)
    this.friends = friends.bind(this)
    this.markBlogList = markBlogList.bind(this)
    this.myCommentList = myCommentList.bind(this)
  }
}

module.exports = new UserController()
